feat: add relayer fee settings
palomachain/paloma pull request #1197
Opened 2024-06-20 08:38 UTC by byte-bandit

# Related Github tickets

- https://github.com/VolumeFi/paloma/issues/1710

# Background

> This change adds the concept of individual
> relayer fees that may be set by any active
> validator for any supported target chain.

# Testing completed

- [ ] test coverage exists or has been added/updated
- [ ] tested in a private testnet

# Breaking changes

- [ ] I have checked my code for breaking changes
- [ ] If there are breaking changes, there is a supporting migration.

2024-06-20 11:17 UTC, maharifu requested changes
Nice one! Just a couple of nitpicks.

2024-06-20 11:17 UTC, maharifu commented on x/treasury/client/cli/tx.go
> +    Sets the relayer fee for the sender to th given multiplicator value.
```suggestion
    Sets the relayer fee for the sender to the given multiplicator value.
```

2024-06-20 11:17 UTC, maharifu commented on x/treasury/client/cli/tx.go
> +			}
Is this needed? We're not allowing values less than 1 below.

2024-06-20 14:03 UTC, byte-bandit commented on proto/palomachain/paloma/treasury/query.proto
> +    option (google.api.http).get = "/palomachain/paloma/treasury/relayer-fee";
I don't know. While there's no clear answer, general consensus seems to shift towards using hyphens over underscores. It's mostly for SEO, but I've become more used to them now.

That being said, all other URIs are using underscore, so better to stick with one than mix.

2024-06-21 08:05 UTC, maharifu approved these changes
LGTM

2024-06-21 08:31 UTC, merged