Add a python faucet
palomachain/paloma pull request #242
Opened 2022-06-17 21:18 UTC by measure-fi

https://www.notion.so/volumefi/EPIC-06-17-Paloma-Public-Testnest-1-d11ce23143c7475a9157acd224933d81

# Background

Temporary super hacky faucet

# Testing completed

- [x] Manually tested

2022-06-17 21:18 UTC, measure-fi commented on pyfaucet/faucet.py
> +db = sqlite3.connect("faucet.db")
BANK and db require preexisting assets on the node.

2022-06-17 21:19 UTC, measure-fi commented on pyfaucet/faucet.py
> +run(host="localhost", port=8479)
Can change this to 8080 and deploy!

2022-06-17 21:19 UTC, measure-fi commented on pyfaucet/faucet.py
> +    return ""
Responses are at the moment almost nonsensical; tell me what the frontend wants and I can send it.

2022-06-18 23:51 UTC, Vizualni requested changes
I am very sorry, but I'll need to block this from getting merged into master. Please move this to a temporary repository instead.

2022-06-19 00:35 UTC, taariq commented
Agreed this should be in its own repo

2022-06-19 02:00 UTC, measure-fi commented
I don't necessarily think this should be merged anywhere, I'm hoping it is a very temporary stopgap. But I can drop it in another repo if we intend to do any maintenance on it (for instance, it is missing rate limiting of IPs and allowing people to go again).

2022-06-19 02:58 UTC, taariq commented
It's good code. Please put it into its own repo. Others will surely use it.

On Sat, Jun 18, 2022, 7:00 PM measure-fi ***@***.***> wrote:

> I don't necessarily think this should be merged anywhere, I'm hoping it is
> a very temporary stopgap. But I can drop it in another repo if we intend to
> do any maintenance on it (for instance, it is missing rate limiting of IPs
> and allowing people to go again).
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/palomachain/paloma/pull/242#issuecomment-1159599534>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAFLLKCBD6UQ3L3UPBKX6HTVPZ5NFANCNFSM5ZDN7W2Q>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2022-06-20 12:41 UTC, closed without merging

2022-06-20 12:49 UTC, measure-fi commented
https://github.com/palomachain/pyfaucet